version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5-stretch
    steps:
      - checkout
      - run:
          name: Test package
          command: |
            mkdir -p ./test-results/go-unit
            #gotestsum is already installed on the circleci docker image
            gotestsum --junitfile ./test-results/go-unit/unit-tests.xml
      - store_test_results:
          path: ./test-results
      - run:
          name: Generate coverage report
          command: go test -race -coverprofile=cov.txt -covermode=atomic
      - codecov/upload:
          file: cov.txt
          flags: "unittests"
workflows:
  version: 2
  test:
    jobs:
      - test
